#!/usr/bin/env python3
"""
Use SerpAPI Google Search to discover Greenhouse and Lever company slugs,
then write them to curated_company_slugs.txt (greenhouse:slug / lever:slug per line).

Usage (from repo root):
  PYTHONPATH=backend .venv/bin/python backend/scripts/discover_companies_to_file.py
"""

from __future__ import annotations

import re
import time
from pathlib import Path

import httpx
from dotenv import load_dotenv

from app.core.config import settings

ROOT = Path(__file__).resolve().parent.parent
SLUGS_FILE = Path(__file__).resolve().parent / "curated_company_slugs.txt"

# Broad query set to maximize company discovery.
GREENHOUSE_QUERIES = [
    "software engineer", "data engineer", "devops engineer", "backend engineer", "frontend engineer",
    "product manager", "designer", "data scientist", "machine learning", "security engineer",
    "sales", "marketing", "customer success", "finance", "legal", "operations",
    "intern", "new grad", "remote", "engineer jobs", "developer jobs",
]
LEVER_QUERIES = [
    "engineer", "developer", "software engineer", "data engineer", "product manager",
    "designer", "sales", "marketing", "operations", "remote", "jobs",
]


def discover_via_serpapi(site: str, query: str, pages: int, api_key: str) -> set[str]:
    companies: set[str] = set()
    full_query = f"site:{site} {query}"
    for page in range(pages):
        params = {
            "engine": "google",
            "q": full_query,
            "start": page * 10,
            "api_key": api_key,
        }
        try:
            resp = httpx.get("https://serpapi.com/search", params=params, timeout=25.0)
            resp.raise_for_status()
            data = resp.json()
        except Exception as e:
            print(f"  SerpAPI error ({site} q={query!r} page={page + 1}): {e}")
            break
        results = (data.get("organic_results") or [])[:10]
        if not results:
            break
        for r in results:
            link = (r.get("link") or "") or ""
            if "boards.greenhouse.io" in site:
                m = re.search(r"boards\.greenhouse\.io/([^/#?]+)/?", link)
            elif "jobs.lever.co" in site:
                m = re.search(r"jobs\.lever\.co/([^/#?]+)/?", link)
            else:
                m = None
            if m:
                slug = m.group(1).strip().lower()
                if slug and slug not in ("jobs", "job", "careers", "www"):
                    companies.add(slug)
        time.sleep(1)
    return companies


def main() -> None:
    load_dotenv(ROOT.parent / ".env")
    api_key = settings.serpapi_api_key or ""
    if not api_key:
        print("SERPAPI_API_KEY not set. Set it in .env and retry.")
        return

    greenhouse_site = "boards.greenhouse.io"
    lever_site = "jobs.lever.co"
    pages_per_query = 10  # ~100 results per query; run takes ~5–8 min

    gh_all: set[str] = set()
    print("Discovering Greenhouse companies via Google (SerpAPI)...")
    for i, q in enumerate(GREENHOUSE_QUERIES, 1):
        found = discover_via_serpapi(greenhouse_site, q, pages_per_query, api_key)
        gh_all.update(found)
        print(f"  [{i}/{len(GREENHOUSE_QUERIES)}] {q!r}: +{len(found)} (total {len(gh_all)})")
        time.sleep(1)

    lever_all: set[str] = set()
    print("Discovering Lever companies via Google (SerpAPI)...")
    for i, q in enumerate(LEVER_QUERIES, 1):
        found = discover_via_serpapi(lever_site, q, pages_per_query, api_key)
        lever_all.update(found)
        print(f"  [{i}/{len(LEVER_QUERIES)}] {q!r}: +{len(found)} (total {len(lever_all)})")
        time.sleep(1)

    # Write incrementally so partial results are saved if script is stopped.
    header = [
        "# Curated Greenhouse and Lever company slugs (one per line).",
        "# Prefix greenhouse: or lever: — used by bulk_crawl_curated_companies.py.",
        "# Auto-generated by discover_companies_to_file.py (SerpAPI Google Search).",
        "",
    ]
    with open(SLUGS_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(header) + "\n")
        for slug in sorted(gh_all):
            f.write(f"greenhouse:{slug}\n")
        for slug in sorted(lever_all):
            f.write(f"lever:{slug}\n")

    total = len(gh_all) + len(lever_all)
    print(f"\nWrote {len(gh_all)} Greenhouse + {len(lever_all)} Lever slugs to {SLUGS_FILE}.")
    print(f"Total: {total} companies.")


if __name__ == "__main__":
    main()
